services:
  doris-fe:
    restart: always
    image: "doris-fe"
    container_name: "doris-fe"
    hostname: "doris-fe"
    environment:
      - FE_SERVERS=fe1:127.0.0.1:9010
      - FE_ID=1
    volumes:
      - /mnt/doris/doris-meta:/opt/apache-doris/fe/doris-meta
      - /mnt/doris/log:/opt/apache-doris/fe/log
      - ./fe.conf:/opt/apache-doris/fe/conf/fe.conf
    network_mode: host
  doris-be:
    restart: always
    image: "doris-be"
    container_name: "doris-be"
    hostname: "doris-be"
    environment:
      - FE_SERVERS=fe1:127.0.0.1:9010
      - BE_ADDR=127.0.0.1:9050
    volumes:
      - /mnt/doris/storage:/opt/apache-doris/be/storage
      - /mnt/doris/script:/docker-entrypoint-initdb.d
      - /mnt/doris/log:/opt/apache-doris/be/log
      - ./be.conf:/opt/apache-doris/be/conf/be.conf
    depends_on:
      - doris-fe
    network_mode: host
  doris-broker:
    restart: always
    image: "doris-broker"
    container_name: "doris-broker"
    hostname: "doris-broker"
    environment:
      - FE_SERVERS=fe1:127.0.0.1:9010
      - BROKER_ADDR=bo1:127.0.0.1:8000
    volumes:
      - ./hdfs-site.xml:/opt/apache-doris/broker/conf/hdfs-site.xml
    depends_on:
      - doris-fe
    network_mode: host